{% set name = "vorbis" %}
{% set version = "1.3.5" %}
{% set sha256 = "6efbcecdd3e5dfbf090341b485da9d176eb250d893e3eb378c428a2db38301ce" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn:  lib{{ name }}-{{ version }}.tar.gz
  url: http://downloads.xiph.org/releases/{{ name }}/lib{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  run_exports:
    - {{ pin_subpackage('libvorbis', max_pin='x.x') }}

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
  host:
    - libogg
  run:
    - libogg

test:
  commands:
    - test -f $PREFIX/lib/libvorbis${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libvorbisenc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libvorbisfile${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\libvorbis.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libvorbis.dll exit 1  # [win]

about:
  home: https://www.xiph.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: "Vorbis audio format"
  description: Lossy audio codec with a fixed point decoder.
  doc_url: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
    - carlodri
