schema_version: 1

context:
  name: vorbis
  version: 1.3.7
  sha256: 270c76933d0934e42c5ee0a54a36280e2d87af1de3cc3e584806357e237afd13

package:
  name: lib${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/xiph/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: lib${{ name }}-${{ version }}.tar.gz
  patches:
    - export_legacy_so_symlinks.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - if: unix
      then: make
  host:
    - libogg
  run:
    - libogg
  run_exports:
    - ${{ pin_subpackage('libvorbis', upper_bound='x.x') }}

tests:
  - package_contents:
      include: 
        - vorbis/codec.h
        - vorbis/vorbisenc.h
        - vorbis/vorbisfile.h
      lib:
        - vorbis
        - vorbisenc
        - vorbisfile
      files:
        - if: win
          then: 
            - Library\\lib\\pkgconfig\\vorbis.pc
            - Library\\lib\\pkgconfig\\vorbisenc.pc
            - Library\\lib\\pkgconfig\\vorbisfile.pc
          else:
            - lib/pkgconfig/vorbis.pc
            - lib/pkgconfig/vorbisenc.pc
            - lib/pkgconfig/vorbisfile.pc
  
about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: Vorbis audio format
  description: Lossy audio codec with a fixed point decoder.
  homepage: https://www.xiph.org/
  documentation: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
    - carlodri
    - martinRenou
